### ISSUE TITLE
Given e.g. a tetrahedron and a point, how do I know the vertices of the face which the point is outside?

### ISSUE THREAD

**Issue by tlycken** [JuliaGeometry/GeometricalPredicates.jl#18]
Consider the following example:

```jl
tetra = Primitive(Point(1.1,1.1,1.1), Point(1.9,1.1,1.1), Point(1.5,1.9,1.1), Point(1.5,1.34,1.9))
point = Point(1.7,1.6,1.5)
intriangle(tetra, point) # -1
```

Given that I know `intriangle(tetra,point) == -1`, can I know *which* of the four corners of the tetrahedron are vertices of the face outside which the point is? In other words, can I, given just the output of `intriangle(tetra, point)`, know which ones of `geta`, `getb`, `getc` and `getd` I should look at to find a plane which `point` is above, given outward-directed plane normals for all faces?

**Comment by skariel** [comment]
yes, it is documented in the README, see image attached below:

![screen shot 2016-09-13 at 9 57 52 am](https://cloud.githubusercontent.com/assets/2347816/18464273/a0598c52-7998-11e6-886f-2525310bc3ea.png)

**Comment by tlycken** [comment]
Maybe I'm just dense (graphical algorithms is pretty far from my normal comfort zone), but I still don't get it :) I guess it's the wording "in front of a" that doesn't tell me as much as it should.

**Comment by skariel** [comment]
let me try to explain. Say you have a Delaunay triangle made of three points A, B and C as in the figure below. Since the red point is outside the triangle the `intriangle` method will give a negative number. Since the point is outside of BC it is in front of A, hence the result is `-1`. The blue point is infant of B, hence it would get  `-2`

![path7268](https://cloud.githubusercontent.com/assets/2347816/18525592/d8f6c9a2-7ac5-11e6-9c1d-422de0a092ab.png)

**Comment by tlycken** [comment]
Ah, that makes a lot of sense. Thanks a lot!
