### ISSUE TITLE
Package does not Compile for Julia v1.0

### ISSUE THREAD

**Issue by pfarndt** [JuliaGeometry/GeometricalPredicates.jl#29]
There are quite a few warnings when compiling the package under Julia v0.7, which let the package compilation break under Julia v1.0.

**Comment by skariel** [comment]
I'll look into it

**Comment by dkarrasch** [comment]
It's because the current master branch is not tagged  (#28), so when you `]add GeometricalPredicates` the lastly tagged version is installed and used (which was written for Julia 0.6). The master branch did receive updates which make it work, but this is invisible to the package manager. If you really need it in Julia 1.0 until a new version release, you could `]add GeometricalPredicates#master`.

**Comment by dkarrasch** [comment]
Fixed on v0.2.0. Just update with the package manager.
